level_1 =[
                 
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"G    R    P      GG          G",
"G                      G     G",
"G  GGG   GG    GG            G",
"G                      GG    G",
"G  R                         G",
"G  GGG    G GG     R         G",
"G                            G",
"G GG   GG              GG    G",
"G          G           G     G",
"G  GG      GGG               G",
"G  GG G          G  GGG      G",
"G  G                     R   G",
"G    G  G  G   G             G",
"GRRRRRRR           GGG       G",
"G      R   G                 G",
"G  RR              GG   GG   G",
"G  RRR                       G",
"G    R GGG             G     G",
"G   R      GG  T   T         G",
"G   R          X   X   R     G",
"G  ER    GG    T   T         G",
"GR RR       XXXX  NXXXX      G",
"GR RRRR     X         X      G",
"GR F  R     X    D    X G    G",
"GRCC HR     X         X GG   G",
"GRRRRRR     XXXTXYXTXXX      G",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    ]


level_2 =[


"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X  P       XXXCCCH           X",
"XXXX   XXXXXXXXXXXXXXYXXX    X",
"XFFX   X         E           X",
"X  X   XXXXXT  TXXXXXXXXXXXXXX",
"X                  X       CCX",
"X     XXXXX   E    X         X",
"XC X  X   X        X       E X",
"XC X  X   X                  X",
"XXXX  T   XXXXXXXXXXXT   TXXXX",
"X                    X       X",
"X     T              X       X",
"X     X              X   E   X",
"X     X    E         X       X",
"X     X        F     XCC     X",
"XXXXXXXXXT   TXXXXXXXXXXX    X",
"X                            X",
"X   XXXXXXXXXXXXXXXXXX       X",
"X   XH             F X E     X",
"X   X                X    E  X",
"X   X  E       CCCCC X A     X",
"X   XXXXXT   TXXXXXXXXXXX    X",
"X                            X",
"X                            X",
"X   XXXXXXXXXXXXXXXXXXXXXXXXXX",
"X               E      E    FX",
"XD                     E    HX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    ]


level_3 =[


"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X P    X       CCCCCCCCCFX D X",
"X      X   X   XXXXXXXXXXT   X",
"X          XE  XFCCCCCC      X",
"X  X   XXXXX   XXXXXXXXXXT   X",
"X  X   X  E              X   X",
"X  X   XXXXXXXXXXXXXXXXX X   X",
"X  X   X       CCC     X X   X",
"X  XXXXX   E   CCC     X X   X",
"X              CCC    HX X   X",
"XXX    XXXXXXXXT   TXXXX X   X",
"X      X  FFF  X   X   E     X",
"X      XECCCCC X   X         X",
"X  E   X  E    X   X         X",
"X  E   XXXXXX  XF  X         X",
"X  E   X       XXXXXXXXXXX   X",
"X      X       X     H XE    X",
"X         E    X       X     X",
"X   VVVVVVVVVVVV       X     X",
"X   V  Z       V   EE  X     X",
"X   V  Z       V       X     X",
"X   VVVVVVVVVVVV   XXXXX     X",
"X                            X",
"X  E         X EEE           X",
"XXXXXXXT   TXXXXXXXXXXXXXYXYXX",
"XF             X   CCC    S  X",
"X      E           CCC       X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    ]

level_4 =[

"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                            X",
"X  TXXXXXXXXXXXXXXXXXXXXXX   X",
"X          EE  CCCCCCCCCFX   X",
"X  TXXXXXXXXXXXXXXXXXXXXXX   X",
"X  X   E                     X",
"X  X   XXXX    XXXXXXXT  TXXXX",
"X  X   X       X             X",
"X  X   XE  Z   XEE           X",
"X  X   X   XXXXXXXXX   Z     X",
"X  X   X   Y       Y         X",
"X  XE  TXXXX       X       F X",
"X  X          CCC  XXXXXXXXXXX",
"X  X          CCC          P X",
"X  X   TXXXX  CCC  XXXXXXXXXXX",
"X  X   X   X       X    X    X",
"X  X   XE  Y       Y  X X X  X",
"X  X   XE  XXXXXXXXX  X X X  X",
"X  X   XXX    X  ZZZZZX X X  X",
"X  X     X XX X  XZZZZX   X  X",
"X  XXXXX X XX XX XXXXXXXXXX  X",
"X  XH  X   XX    X      D X  X",
"X  X   XXXXXXXXXXX        X  X",
"X                   Z     X  X",
"X      E                  X  X",
"X  XXXXXXXX      X     TXXX  X",
"X  XCCCCCCE     EX           X",
"XXXXXXXXXXXXXXXXXXXXXXXTXXXXXX",


    ]


level_5 =[


"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XZCCCCCCCCCCCCC       XT     X",
"XCCCCCCCCCCCCCC            D X",
"XHCCCCCCCCCCCCC       XT     X",
"XXXXXXXXXXXXXXXXXXXXXXXXX    X",
"XIIIIIIIIIIIYXXXXXXXXFFFXZ   X",
"XIXXXXXXXX   E      X   X    X",
"XIX   XXXX F      H X   X    X",
"XIX   XXXX     S    X   X    X",
"XII   XXXX          X  XXX   X",
"XXT   TXXXXXXXXXXXXXX  XXX   X",
"X                      XXX   X",
"X  Z                         X",
"X          XXXXXXXXX         X",
"X  XXXX    X   Z        X    X",
"X  XXXX    XF           TXXXXX",
"X  XXXXZ   XXXXXXXXXZ     CCCX",
"X  XCCCC                TXXXXX",
"X  XXXXXXXXXXXXXXX      XCCC X",
"X      CCCCCCCCXXX Z    XCCC X",
"X                       XCCC X",
"X  X   Z           XXXXXX    X",
"X  X                   Z     X",
"X  XXXXXXXXXXXXXXXXZZ       ZX",
"X      T        XXXXXXXXXXXXXX",
"X         EEEEEE             X",
"X      T  EEEEEE           P X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]


level_6 =[


"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X  V               TXX       X",
"X QV   EE              XX    X",
"XVVV               TXXXXX  P X",
"X  E       Z  XXXXXXXXXXXXXXXX",
"X      E      X            F X",
"XXXXXXXXXXXX  X   XXXXXXX    X",
"X   CCCCCCFX  X   X  L HX    X",
"X   XXXXXXXT  T   X     X    X",
"X                 X   L X    X",
"X   XXXXXXXXXXXXYIX     X    X",
"X   XF A  EE    IIX     XZ   X",
"X   XF    EE    XXX     T    X",
"X   XXXXXXXXXXXXXXXX         X",
"X   XH  L  X    FF X         X",
"X   XC      L      X    T    X",
"X   XC Z           X    X    X",
"X   XC     X       X    X    X",
"X   XXXXXXXXXX   XXX    X    X",
"X                  X    X    X",
"XXXXXXXXXXXXXT   TXXX  XX    X",
"XCCC               X         X",
"XCCC   ZZ          X   LLLL  X",
"XCCC        XT   TXXXX L  L  X",
"XXXXXXXXXXXXX        X       X",
"X     L              X       X",
"X  D       ZZZ       X B     X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]



level_7 =[

"         K                   ",
"XXXXXXXTXYXTXXXXXXXXXXXXXXXXXX",
"X  P                         X",
"X                   XXXX     X",
"XXXXXXXXXXXXX       XXXXL    X",
"X                   XXXX     X",
"X  L                         X",
"X              XXXX          X",
"X  XXXX        XXXX          X",
"X  XXXXL       XXXX          X",
"X  XXXX                      X",
"X          L           XXXX  X",
"X                      XXXX  X",
"X          XXXX        XXXX  X",
"X XXXX     XXXX              X",
"X XXXX     XXXX     XXXX     X",
"X XXXX              XXXX     X",
"X       XXXX        XXXX     X",
"X       XXXX         J       X",
"X       XXXX             L   X",
"X  XXXX              XXXX    X",
"X  XXXX     XXXXT    XXXX    X",
"X  XXXX   L X        XXXX    X",
"XH          X  XT          H X",
"XXXXXXXXXXXXX  XXXXXXXXXXXXXXX",
"X  E   E    T  T    E  E     X",
"X                      D     X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]


level_8 =[

"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XCCCCCCCCCCCCCCCCCCCCCCCCCCCCX",
"XCCCCCCCCCCCCCCCCCCCCCCCCCCCCX",
"XCCCCCCCCCCCCCCCCCCCCCCCCCCCCX",
"XCCCCCCCCCCCCCCCCCCCCCCCCCCCCX",
"XCCCCCCCCCCCCCCCCCCCCCCCCCCCCX",
"XCCCCCCCCCCCCCCCCCCCCCCCCCCCCX",
"XCCCCCCXXXXXXXXXXXXXXCCCCCCCCX",
"XCCCCCCXL L L L L L XCCCCCCCCX",
"XCCCCCCXZ Z Z Z Z ZZXCCCCCCCCX",
"XCCCCCCXZE E E E E ZXCCCCCCCCX",
"XCCCCCCX EVVVVVVEZLZXCCCCCCCCX",
"XCCCCCCXZ V P  V E  XCCCCCCCCX",
"XCCCCCCX EV    VLZ ZXCCCCCCCCX",
"XCCCCCCXZEVV  VVE   XCCCCCCCCX",
"XCCCCCCXZ  V  V  ZZZXCCCCCCCCX",
"XCCCCCCXL LV  V L L XCCCCCCCCX",
"XCCCCCCXXXXT  TXXXXXXCCCCCCCCX",
"XCCCCCCCX         XCCCCCCCCCCX",
"XCCCCCCCX         XCCCCCCCCCCX",
"XCCCCCCCX         XCCCCCCCCCCX",
"XCCCCCCCXXXT   TXXXCCCCCCCCCCX",
"XCCCCCCCX         XCCCCCCCCCCX",
"XCCCCCCCI         ICCCCCCCCCCX",
"XCCCCCCCXXT     TXXCCCCCCCCCCX",
"XCCCCCCCCCX  M  XCCCCCCCCCCCCX",
"XCCCCCCCCCX     XCCCCCCCCCCCCX",
"XXXXXXXXXXXTXYXTXXXXXXXXXXXXXX",

]
